import './globals.css'
import Header from './components/header/Header'


export const metadata = {
  title: 'اسنپ فود | سفارش آنلاین غذا از تمامی رستوران‌ ها و فست فودها',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <Header/>
        {children}
        </body>
    </html>
  )
}
