

export const metadata = {
  title: ' ورود یا عضویت',
  description: 'Generated by create next app',
}

export default function LoginLayout({ children }) {
  return (
    <html>
      <body>
    
        {children}
        </body>
    </html>
  )
}
  